language: python
group: travis_latest

git:
  depth: 3
  quiet: true

python:
- 3.6
- 3.7

os:
- linux

install: pip install -e .[tests]

script:
- pytest
- flake8
- mypy .

after_success:
- if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
  pytest --cov --cov-config=setup.cfg;
  coveralls;
  fi
